// Labelling for the deal activity stream tab.
//
// The tab renders the FULL audit stream (system events included), so it must be
// called "Activity (N)" — never "Communication (N)", which would imply N
// customer-facing interactions. System events are preserved and counted
// separately so the UI can distinguish them.

import { isSystemActivity, isMeaningfulCustomerInteraction } from "@/lib/activity-log";

export interface ActivityStreamItem {
  activity_type?: string | null;
}

export interface ActivityStreamCounts {
  total: number;
  /** Customer-facing interactions (calls, meetings, emails, demos, decisions…). */
  customer: number;
  /** Internal audit events generated by the system. */
  system: number;
}

export function countActivityStream(items: ActivityStreamItem[] = []): ActivityStreamCounts {
  let customer = 0;
  let system = 0;
  for (const a of items) {
    if (isSystemActivity(a.activity_type)) system++;
    else if (isMeaningfulCustomerInteraction(a.activity_type)) customer++;
  }
  return { total: items.length, customer, system };
}

/** Tab label for the full audit stream. */
export function activityTabLabel(items: ActivityStreamItem[] = []): string {
  return `Activity (${items.length})`;
}

/** Human summary shown under the timeline heading. */
export function activityStreamSummary(items: ActivityStreamItem[] = []): string {
  const { customer, system } = countActivityStream(items);
  const other = items.length - customer - system;
  const parts = [
    `${customer} customer interaction${customer === 1 ? "" : "s"}`,
    `${system} system event${system === 1 ? "" : "s"}`,
  ];
  if (other > 0) parts.push(`${other} internal note${other === 1 ? "" : "s"}`);
  return parts.join(" · ");
}
