import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { CustomerLogo } from './CustomerLogo';
import {DirectoryMediaEditor,type MediaPatch} from './DirectoryMediaEditor';
import { ISO_COUNTRIES } from '@/data/iso-countries';
import { countryCode, countryName } from '@/lib/customer-explorer';
import { clientKey, reviewDirectoryImport, validateDirectoryInput, type DirectoryClient, type DirectoryInput, type ImportReview } from '@/lib/customer-directory';

const empty: DirectoryInput={client_id:'',name:'',country:'PT',sector:null,active:null,visible:true,evidence_status:'unconfirmed',evidence_note:null};
export function DirectoryManager({rows,onSave,onImport,onClose,onLogoChange,onMediaSave,onKeepSector,preview=false}:{rows:DirectoryClient[];onSave:(input:DirectoryInput,current?:DirectoryClient)=>Promise<void>;onImport:(items:ImportReview[])=>Promise<void>;onClose:()=>void;onLogoChange?:(id:string,url:string|null,dark?:boolean)=>void;onMediaSave?:(client:DirectoryClient,patch:MediaPatch)=>Promise<void>;onKeepSector?:(client:DirectoryClient)=>Promise<void>;preview?:boolean}) {
 const [search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[current,setCurrent]=useState<DirectoryClient>(),[form,setForm]=useState<DirectoryInput>(),[review,setReview]=useState<ImportReview[]>(),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const sectors=useMemo(()=>[...new Set(rows.map(r=>r.sector).filter(Boolean))].sort() as string[],[rows]);
 const logoClient=current?rows.find(r=>r.id===current.id)||current:undefined;
 const uploadLogo=async(file?:File)=>{if(!file||!current||!onLogoChange)return;setError('');try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>256_000)throw new Error('Choose a PNG, JPEG or WebP logo up to 256 KB.');const url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read logo.'));reader.readAsDataURL(file);});onLogoChange(current.id,url);setMessage('Logo updated in the local demo. Reloading resets these changes.');}catch(e){setError(e instanceof Error?e.message:'Unable to read logo.');}};
 const filtered=rows.filter(r=>(!search||[r.name,r.client_id,r.country,countryName(r.country),countryCode(r.country)].some(v=>v?.toLowerCase().includes(search.trim().toLowerCase())))&&(filter==='all'||filter==='hq'&&r.source_kind==='hq'||filter==='missing'&&!r.sector||filter==='review'&&r.evidence_status!=='validated'||filter==='hidden'&&!r.visible||filter==='source_changed'&&r.source_sector_changed));
 const keepSector=async()=>{if(!current||!onKeepSector)return;setError('');setBusy(true);try{await onKeepSector(current);setForm(undefined);setMessage('Source change reviewed. The Explorer sector was kept.');}catch(e){setError(e instanceof Error?e.message:'Unable to acknowledge source change.');}finally{setBusy(false);}};
 const edit=(r?:DirectoryClient)=>{setCurrent(r);setForm(r?{client_id:r.client_id!,name:r.name,country:r.country||'',sector:r.sector,active:r.active,visible:r.visible,evidence_status:r.evidence_status,evidence_note:r.evidence_note}: {...empty});setError('');setMessage('');};
 const save=async()=>{setError('');setBusy(true);try{const input=validateDirectoryInput(form!);if(!current&&rows.some(r=>clientKey(r.client_id)===clientKey(input.client_id)))throw new Error('Client ID already exists. Edit the existing record instead.');await onSave(input,current);setForm(undefined);setMessage('Customer saved. The Explorer has been updated.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}};
 const readFile=async(file?:File)=>{if(!file)return;setError('');setReview(undefined);try{if(file.size>5_000_000)throw new Error('File exceeds 5 MB.');const book=XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:false});const sheet=book.Sheets[book.SheetNames.includes('Clients_Master')?'Clients_Master':book.SheetNames[0]];const values=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{raw:false,defval:''});if(values.length>5000)throw new Error('Maximum 5,000 rows per import.');if(!values.length||!('Client ID' in values[0]))throw new Error('Expected headers: Client ID, Client Name, Country, Sector.');setReview(reviewDirectoryImport(values,rows));}catch(e){setError(e instanceof Error?e.message:'Unable to read this file.');}};
 const applyImport=async()=>{setError('');setBusy(true);try{await onImport(review!.filter(r=>r.action==='new'||r.action==='update'));setMessage('Reviewed HQ customer rows imported. Partner records were not changed.');setReview(undefined);}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}};
 return <section className="ce-manager"><div className="ce-manager-heading"><div><h1>Manage customer directory</h1><p>HQ administration · partner source records stay in their existing module.{preview?' Local demo: changes stay in this browser session.':''}</p></div><button onClick={onClose}>Back to map</button></div>
 <div className="ce-manager-tools"><button onClick={()=>edit()}>Add HQ customer</button><label className="ce-import-button">Review Excel / CSV<input type="file" accept=".xlsx,.csv" onChange={e=>{readFile(e.target.files?.[0]);e.target.value='';}}/></label><input aria-label="Search directory" placeholder="Search name, ID or country" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Review filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All customers</option><option value="hq">HQ customers</option><option value="missing">Missing sector</option><option value="review">Needs sector validation</option><option value="source_changed">Source sector changed</option><option value="hidden">Hidden from Explorer</option></select></div>
 <p>Partner identity and country follow Clients &amp; Licenses. An Explorer sector override takes priority; it does not change the partner source.</p>
 {rows.some(r=>r.source_sector_changed)&&<p role="status" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-amber-950">{rows.filter(r=>r.source_sector_changed).length} source sector changes need HQ review. The Explorer classifications have been preserved. <button onClick={()=>{setFilter('source_changed');setSearch('');}}>Review source changes</button></p>}
 {error&&<p role="alert" className="ce-manager-error">{error}</p>}{message&&<p role="status">{message}</p>}
 {form&&logoClient&&onMediaSave&&!preview&&<DirectoryMediaEditor client={logoClient} onSave={onMediaSave}/>}
 {form&&current?.source_kind==='partner'&&<section aria-label="Sector source review" className="rounded-lg border p-3"><h2>Sector source of truth</h2><p>Clients &amp; Licenses: {current.source_sector||'Sector not supplied'}</p><p>Explorer: {current.sector||'Sector to confirm'} · {current.has_sector_override?(current.evidence_status==='validated'?'HQ-validated override':'Explorer override · not HQ-validated'):'Following Clients & Licenses'}</p>{current.source_sector_changed&&<><p role="alert">Source sector changed since the last review: {current.source_sector_at_review||'Not supplied'} → {current.source_sector||'Not supplied'}. Review the Explorer classification before accepting this change.</p>{onKeepSector&&<button type="button" disabled={busy} onClick={keepSector}>Reviewed: keep Explorer sector</button>}</>}</section>}
 {form&&current&&logoClient&&preview&&onLogoChange&&<div className="ce-logo-editor"><CustomerLogo client={logoClient}/><label>Customer logo · local demo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{uploadLogo(e.target.files?.[0]);e.target.value='';}}/></label><label><input type="checkbox" checked={!!logoClient.logo_dark} onChange={e=>onLogoChange(current.id,logoClient.logo_url||null,e.target.checked)}/>Dark background for white logos</label><button type="button" onClick={()=>{onLogoChange(current.id,null);setMessage('Logo removed in the local demo.');}}>Remove logo</button><p>Use a confirmed company logo. PNG, JPEG or WebP, maximum 256 KB. Changes apply immediately to the prototype only.</p></div>}
 {form&&<form className="ce-editor" onSubmit={e=>{e.preventDefault();save();}}><h2>{current?`Edit ${current.name}`:'New HQ customer'}</h2>{current?.source_kind==='partner'&&<p>Name, ID, country and lifecycle are synchronized from the partner's client list. Only Explorer sector and visibility can be changed here.</p>}<div className="ce-editor-grid">
 <label>Client ID<input required value={form.client_id} disabled={!!current} onChange={e=>setForm({...form,client_id:e.target.value})}/></label>
 <label>Company name<input required value={form.name} disabled={current?.source_kind==='partner'} onChange={e=>setForm({...form,name:e.target.value})}/></label>
 <label>Country<select required value={form.country} disabled={current?.source_kind==='partner'} onChange={e=>setForm({...form,country:e.target.value})}><option value="">Choose country</option>{!ISO_COUNTRIES.some(c=>c.code===form.country)&&form.country&&<option>{form.country}</option>}{ISO_COUNTRIES.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label>
 <label>Sector<select value={form.sector||''} onChange={e=>setForm({...form,sector:e.target.value||null,evidence_status:'unconfirmed'})}><option value="">Sector to confirm</option>{sectors.map(s=><option key={s}>{s}</option>)}</select></label>
 <label>Lifecycle<select value={form.active===null?'unknown':form.active?'active':'historical'} disabled={current?.source_kind==='partner'} onChange={e=>setForm({...form,active:e.target.value==='unknown'?null:e.target.value==='active'})}><option value="unknown">Unconfirmed</option><option value="active">Active</option><option value="historical">Historical</option></select></label>
 <label>Sector validation<select value={form.evidence_status} onChange={e=>setForm({...form,evidence_status:e.target.value as DirectoryInput['evidence_status']})}><option value="unconfirmed">Unconfirmed</option><option value="suggested">Suggested</option><option value="validated">Validated by HQ</option></select></label>
 <label>Source / validation note<input value={form.evidence_note||''} onChange={e=>setForm({...form,evidence_note:e.target.value||null})}/></label><label className="ce-editor-checkbox"><input type="checkbox" checked={form.visible} onChange={e=>setForm({...form,visible:e.target.checked})}/>Visible in Explorer</label></div><p>HQ contact: customercare@manwinwin.com. No customer contacts or commercial details are published.</p><button disabled={busy} type="submit">{busy?'Saving…':'Save customer'}</button><button type="button" onClick={()=>setForm(undefined)} disabled={busy}>Cancel</button></form>}
 {review&&<section className="ce-import-review"><h2>Import review</h2><p>{review.filter(r=>r.action==='new').length} new · {review.filter(r=>r.action==='update').length} HQ updates · {review.filter(r=>r.action==='skip').length} skipped · {review.filter(r=>r.action==='error').length} errors</p><p>Validated sectors are not automatically approved from a file. Updates replace the reviewed HQ name, country, sector and evidence; known lifecycle and visibility are preserved.</p><div className="ce-manager-scroll"><table><thead><tr><th>Row</th><th>ID</th><th>Customer</th><th>Action</th><th>Review</th></tr></thead><tbody>{review.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.input.client_id}</td><td>{r.input.name}</td><td>{r.action}</td><td>{r.message}</td></tr>)}</tbody></table></div><button disabled={busy||review.some(r=>r.action==='error')||!review.some(r=>r.action==='new'||r.action==='update')} onClick={applyImport}>Confirm reviewed HQ import</button><button disabled={busy} onClick={()=>setReview(undefined)}>Cancel import</button></section>}
 <p>{filtered.length} customers · showing first 100. Use search to narrow the list.</p><div className="ce-manager-scroll"><table><thead><tr><th>ID</th><th>Customer</th><th>Country</th><th>Source</th><th>Sector</th><th>Validation</th><th>Visibility</th><th></th></tr></thead><tbody>{filtered.slice(0,100).map(r=><tr key={r.id}><td>{r.client_id}</td><td>{r.name}</td><td>{countryName(r.country)}</td><td>{r.source_kind==='hq'?'HQ':r.partner}</td><td>{r.sector||'Sector to confirm'}</td><td>{r.evidence_status}{r.validated_at&&<small> · {new Date(r.validated_at).toLocaleDateString()}</small>}</td><td>{r.visible?'Visible':'Hidden'}</td><td><button onClick={()=>edit(r)}>Edit</button></td></tr>)}</tbody></table></div></section>;
}
