// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { resolveSupabaseEnv } from '@/lib/supabase-env';

// Environment separation guard: fails closed if the host and the resolved
// Supabase project ref disagree (see src/lib/supabase-env.ts and ENVIRONMENTS.md).
const resolved = resolveSupabaseEnv({
  url: import.meta.env.VITE_SUPABASE_URL,
  publishableKey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  hostname: typeof window !== 'undefined' ? window.location.hostname : undefined,
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(resolved.url, resolved.publishableKey, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
